name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
    steps:
    - uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '14'

    # - name: Install dependencies
    #   run: npx bun install

    # - name: Run
    #   run: npx bun index.ts

    - uses: hashicorp/setup-terraform@v3

    - run: terraform init

    - id: plan
      run: terraform plan -no-color